FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash cephalon

RUN mkdir /etc/cephalon

RUN mkdir /var/lib/cephalon

RUN chown cephalon:cephalon /etc/cephalon /var/lib/cephalon

WORKDIR /home/cephalon

COPY --chown=cephalon:cephalon linux64/* ./run.sh /home/cephalon/

USER cephalon

CMD ["/home/cephalon/run.sh"]
